name: "experiment"
override: true
sle_gan_folder: "/drive/My Drive/ml/2021/dung-sle-gan/sle_gan"
data_folder: "/drive/My Drive/ml/datasets/dung_256x256_sle_gan_ready"
resolution: 256 #Either 256, 512 or 1024. Default is 512.
generator_weights: False
discriminator_weights: False
batch_size: 1
epochs: 1000
G_learning_rate: 2e-4
D_learning_rate: 2e-4
diff_augment: True
diff_augment_policies: "color,translation,cutout"
fid: False
fid_frequency: 1 #FID will be evaluated at this frequency (epochs)
fid_number_of_images: 128 #This many images will be used for the FID calculation

